#!/bin/bash
if [ "$SOURCE_BRANCH" = "master" ]
then
  # just promote the latest tag
  latest="$(cat README.md | awk '/badge\/latest/' | sed 's/^.*latest-\(.*\)-blue.svg.*/\1/' | sed 's/--/-/g')"
  docker pull $DOCKER_REPO:$latest
  docker tag $DOCKER_REPO:$latest $IMAGE_NAME
else
  docker build --build-arg branch=${SOURCE_BRANCH#*/} -f $DOCKERFILE_PATH -t $IMAGE_NAME .
fi
