#!/usr/bin/env bash

SHIP="$1"
: ${URBIT_IMAGE:="asssaf/urbit:latest"}

if [ -z "$SHIP" ]
then
	>&2 echo "Usage: $(basename $0) <ship>"
	exit 1
fi

docker run -ti --rm \
	--net host \
	-v $(pwd)/${SHIP}:/srv/${SHIP} \
	--workdir /srv \
	--user $(id -u):$(id -g) \
	${URBIT_IMAGE} ${SHIP}
