#!/usr/bin/env bash

SHIP="$1"
IMAGE="asssaf/urbit"

if [ -z "$SHIP" ]
then
	>&2 echo "Usage: $(basename $0) <ship>"
	exit 1
fi

docker run -t -d --rm \
	--net host \
	-v $(pwd)/${SHIP}:/srv/${SHIP} \
	--workdir /srv \
	--user $(id -u):$(id -g) \
	${IMAGE} -d ${SHIP}
